### ISSUE TITLE
Remover código de formulários

### ISSUE THREAD

**Issue by rslana** [jjthegomes/sgcr-java#1]
Remover de todos os formulários o campo código (onde será feito o auto incremento) e remover o combo box com o usuário (Ex: Criar corrida, onde seleciona qual organizador será). Com login implementado, é possível pegar o id do usuário logado.

- [x] Administrador;

- [x] Atleta;

- [x] Corrida;

- [x] Inscrição;

- [x] Kit;

- [x] Organizador;

- [x] Percurso;

- [x] Pontuação; (Incorporado em manter ranking);

- [x] Produto;

- [x] Produto Kit;

- [x] Ranking;

**Comment by rslana** [comment]
Os campos com código devem estar como hidden e name="hiddenIdCorrida" por exemplo. Com isso, fazer as devidas alterações nos controllers também.

**Comment by jjthegomes** [comment]
Campos codigos tipo hidden e construtor sem id criados
