### ISSUE TITLE
Adicionar campo número e ativo na classe Corrida.

### ISSUE THREAD

**Issue by rslana** [jjthegomes/sgcr-java#2]
Adicionar campo número e ativo na classe modelo Corrida, bem como alterar o jsp de manter, DAO e Controller

**Comment by RSLana** [comment]
Adicionar campo número e ativo na classe  de modelo Corrida

**Comment by jjthegomes** [comment]
Alterações concluidas e commitadas

**Comment by rslana** [comment]
Adicionei o campo edição também... Tudo certo.
